#!/usr/bin/env python3
"""PreToolUse hook: block edits to lock files and other generated manifests.

Lock files should be regenerated by the package manager, not hand-edited.
Exit code 2 blocks the tool call and surfaces the stderr message to Claude.
"""
import json
import os
import sys

BLOCKED_BASENAMES = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "uv.lock",
    "poetry.lock",
    "pdm.lock",
}


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0

    file_path = data.get("file_path") or data.get("tool_input", {}).get(
        "file_path", ""
    )
    if not file_path:
        return 0

    base = os.path.basename(file_path.replace("\\", "/")).lower()
    if base in BLOCKED_BASENAMES:
        sys.stderr.write(
            f"Blocked: '{base}' is a lock file and must not be edited by hand. "
            "Run the package manager (npm/uv/poetry) to regenerate it instead.\n"
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
